services:
  - type: web
    name: jashu-backend
    runtime: docker
    buildCommand: "docker build -t jashu-backend ."
    startCommand: "docker run -p $PORT:8080 jashu-backend"
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /actuator/health
    autoDeploy: true